### ISSUE TITLE
Update to Ejs 2.0

### ISSUE THREAD

**Issue by hilquiasrodrigues** [dwightjack/grunt-ejs-render#8]
The new version of [Ejs](https://github.com/mde/ejs) have a bunch of new features.
If is possible, please update.

Thanks.

**Comment by dwightjack** [comment]
Hi,

If possible I'd advice you to switch to [this other plugin](https://github.com/dwightjack/grunt-tmpl-render). It's template engine agnostic, so you can use whatever you want to render your templates.

In the docs there's an example on how to use ejs.

**Comment by hilquiasrodrigues** [comment]
Thanks.
